# Generated by Django 5.0.7 on 2025-01-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
